backend:
  name: git-gateway
  branch: netlify-prod # Branch to update (optional; defaults to master)

#local_backend: true

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
#publish_mode: editorial_workflow # For Drafts

collections:
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "content/about" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Titulo (English)", name: "title_eng", widget: "string" }
      - { label: "Cuerpo (Castellano)", name: "body", widget: "markdown" }
      - { label: "Cuerpo (English)", name: "body_eng", widget: "markdown" }
  - name: "exhibitions" # Used in routes, e.g., /admin/collections/blog
    label: "Exhibitions" # Used in the UI
    folder: "content/exhibitions" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Mostrar", name: "show", widget: "boolean" }
      - { label: "Titulo (English)", name: "title_eng", widget: "string" }
      - { label: "Cuerpo (Castellano)", name: "body", widget: "markdown" }
      - { label: "Cuerpo (English)", name: "body_eng", widget: "markdown" }
  - name: "bio" # Used in routes, e.g., /admin/collections/blog
    label: "Bio" # Used in the UI
    folder: "content/bio" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
  - name: "bio_statement" # Used in routes, e.g., /admin/collections/blog
    label: "Bio Statement" # Used in the UI
    folder: "content/bio_statement" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Cuerpo (Castellano)", name: "body", widget: "markdown" }
      - { label: "Cuerpo (English)", name: "body_eng", widget: "markdown" }
  - name: "works" # Used in routes, e.g., /admin/collections/blog
    label: "Works" # Used in the UI
    folder: "content/obras" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Fecha de publicación",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          format: "LLL",
        }

      - { label: "Imagen de portada", name: "thumbnail", widget: "image" }
      - {
          label: "Link de Vimeo para video de portada",
          name: "vimeo_front_url",
          widget: "string",
        }
      - {
          label: "Link de Vimeo para video de portada",
          name: "vimeo_video_gallery",
          widget: "list",
        }
      - { label: "Hero Image", name: "hero_img", widget: "image" }
      - {
          label: "Mostrar en selección",
          name: "front_page",
          widget: "boolean",
          default: false,
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Titulo (English)", name: "title_eng", widget: "string" }
      - { label: "Medidas", name: "medidas", widget: "string" }
      - { label: "Medidas (English)", name: "medidas_eng", widget: "string" }
      - { label: "Año", name: "year", widget: "number", value_type: "int" }
      - { label: "Materiales (Castellano)", name: "material", widget: "string" }
      - {
          label: "Materiales (English)",
          name: "material_eng",
          widget: "string",
        }
      - { label: "Locación", name: "locacion", widget: "string" }
      - { label: "Locación (English)", name: "locacion_eng", widget: "string" }
      - { label: "Técnica", name: "tecnica", widget: "string" }
      - { label: "Técnica (English)", name: "tecnica_eng", widget: "string" }
      - { label: "Cuerpo (Castellano)", name: "body", widget: "markdown" }
      - { label: "Cuerpo (English)", name: "body_eng", widget: "markdown" }
